project_name: flog

builds:
  - id: flog
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - Update README.md
    - Merge pull request
    - Merge branch

archives:
  - format: binary

release:
  github:
    owner: jsirianni
    name: flog
  name_template: '{{.Tag}}'

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - flog
    image_templates:
      - "ghcr.io/jsirianni/flog-amd64:latest"
      - "ghcr.io/jsirianni/flog-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/jsirianni/flog"
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
  - goos: linux
    goarch: arm64
    ids:
      - flog
    image_templates:
      - "ghcr.io/jsirianni/flog-arm64:latest"
      - "ghcr.io/jsirianni/flog-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/jsirianni/flog"
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/jsirianni/flog:latest"
    image_templates:
      - "ghcr.io/jsirianni/flog-amd64:latest"
      - "ghcr.io/jsirianni/flog-arm64:latest"
    skip_push: false
  - name_template: "ghcr.io/jsirianni/flog:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/jsirianni/flog-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/flog-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
