name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  # Make sure package write permission is always enabled, even
  # for Dependabot pull requests.
  packages: write

# Prevent multiple runs on the same branch. This is important for webhooks
# that must be run in order.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20"

      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.15.2
          args: release --skip-publish --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

